"""
Support Ticket Service

Handles creation, management, and resolution of student support tickets.
Includes email notifications for ticket updates.
"""

from datetime import datetime
from typing import Dict, Any, List, Optional
from supabase import Client
from .email_service import get_email_service
from .notification_service import get_notification_service


class SupportTicketService:
    """Service for managing support tickets"""
    
    TICKET_CATEGORIES = [
        'Payment Issues',
        'Technical Support',
        'Course Content',
        'Account Access',
        'Session Scheduling',
        'Recordings',
        'Assignments',
        'Certificates',
        'General Inquiry'
    ]
    
    def __init__(self, supabase_client: Client):
        self.supabase = supabase_client
        self.email_service = get_email_service()
        self.notification_service = get_notification_service(supabase_client)
    
    def create_ticket(
        self,
        student_id: str,
        subject: str,
        description: str,
        category: Optional[str] = None,
        priority: str = 'medium'
    ) -> Dict[str, Any]:
        """
        Create a new support ticket
        
        Args:
            student_id: UUID of the student creating the ticket
            subject: Ticket subject/title
            description: Detailed description of the issue
            category: Ticket category (optional)
            priority: Priority level (low, medium, high, urgent)
            
        Returns:
            Dict with success status and ticket data
        """
        try:
            # Create ticket (ticket_number is auto-generated by trigger)
            ticket_data = {
                'student_id': student_id,
                'subject': subject,
                'description': description,
                'category': category,
                'priority': priority,
                'status': 'open'
            }
            
            response = self.supabase.table('support_tickets').insert(ticket_data).execute()
            
            if not response.data:
                return {'success': False, 'error': 'Failed to create ticket'}
            
            ticket = response.data[0]
            
            # Get student info for notifications
            student_response = self.supabase.table('profiles').select('*').eq('id', student_id).execute()
            student = student_response.data[0] if student_response.data else {}
            
            # Send confirmation email to student
            self._send_ticket_created_email(
                student_email=student.get('email'),
                student_name=student.get('full_name'),
                ticket_number=ticket['ticket_number'],
                subject=subject
            )
            
            # Notify all admins
            self._notify_admins_new_ticket(
                ticket_id=ticket['id'],
                ticket_number=ticket['ticket_number'],
                student_name=student.get('full_name'),
                subject=subject,
                priority=priority
            )
            
            print(f"[Support Ticket] Created ticket {ticket['ticket_number']}")
            
            return {
                'success': True,
                'ticket': ticket
            }
            
        except Exception as e:
            print(f"[Support Ticket] Error creating ticket: {str(e)}")
            return {'success': False, 'error': str(e)}
    
    def add_reply(
        self,
        ticket_id: str,
        author_id: str,
        message: str,
        is_internal_note: bool = False
    ) -> Dict[str, Any]:
        """
        Add a reply to a support ticket
        
        Args:
            ticket_id: UUID of the ticket
            author_id: UUID of the person replying
            message: Reply message content
            is_internal_note: If True, only admins can see this reply
            
        Returns:
            Dict with success status and reply data
        """
        try:
            # Create reply
            reply_data = {
                'ticket_id': ticket_id,
                'author_id': author_id,
                'message': message,
                'is_internal_note': is_internal_note
            }
            
            response = self.supabase.table('ticket_replies').insert(reply_data).execute()
            
            if not response.data:
                return {'success': False, 'error': 'Failed to add reply'}
            
            reply = response.data[0]
            
            # Update ticket updated_at timestamp
            self.supabase.table('support_tickets').update({
                'updated_at': datetime.utcnow().isoformat()
            }).eq('id', ticket_id).execute()
            
            # Get ticket and author info
            ticket_response = self.supabase.table('support_tickets').select(
                'ticket_number, subject, student_id, profiles!support_tickets_student_id_fkey(full_name, email)'
            ).eq('id', ticket_id).execute()
            
            if not ticket_response.data:
                return {'success': True, 'reply': reply}
            
            ticket = ticket_response.data[0]
            author_response = self.supabase.table('profiles').select('*').eq('id', author_id).execute()
            author = author_response.data[0] if author_response.data else {}
            
            # Send notification (skip if internal note)
            if not is_internal_note:
                student = ticket.get('profiles', {})
                student_id = ticket['student_id']
                
                # If author is admin, notify student
                if author.get('role') == 'admin':
                    self._send_ticket_reply_email(
                        recipient_email=student.get('email'),
                        recipient_name=student.get('full_name'),
                        ticket_number=ticket['ticket_number'],
                        subject=ticket['subject'],
                        reply_message=message,
                        author_name=author.get('full_name', 'Support Team')
                    )
                    
                    # Create in-app notification
                    self.notification_service.create_notification(
                        user_id=student_id,
                        notification_type='system',
                        title='Support Ticket Reply',
                        message=f"New reply on ticket {ticket['ticket_number']}",
                        link=f"/support/{ticket_id}"
                    )
                else:
                    # If student replied, notify admins
                    self._notify_admins_ticket_reply(
                        ticket_id=ticket_id,
                        ticket_number=ticket['ticket_number'],
                        student_name=student.get('full_name'),
                        subject=ticket['subject']
                    )
            
            return {
                'success': True,
                'reply': reply
            }
            
        except Exception as e:
            print(f"[Support Ticket] Error adding reply: {str(e)}")
            return {'success': False, 'error': str(e)}
    
    def update_ticket_status(
        self,
        ticket_id: str,
        status: str,
        admin_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """Update ticket status"""
        try:
            update_data = {
                'status': status,
                'updated_at': datetime.utcnow().isoformat()
            }
            
            # If resolving/closing, track resolved_at and resolved_by
            if status in ['resolved', 'closed']:
                update_data['resolved_at'] = datetime.utcnow().isoformat()
                if admin_id:
                    update_data['resolved_by'] = admin_id
            
            response = self.supabase.table('support_tickets').update(update_data).eq('id', ticket_id).execute()
            
            if not response.data:
                return {'success': False, 'error': 'Ticket not found'}
            
            ticket = response.data[0]
            
            # Notify student of status change
            ticket_detail = self.supabase.table('support_tickets').select(
                'ticket_number, subject, student_id, profiles!support_tickets_student_id_fkey(full_name, email)'
            ).eq('id', ticket_id).execute()
            
            if ticket_detail.data:
                ticket_info = ticket_detail.data[0]
                student = ticket_info.get('profiles', {})
                
                self._send_status_update_email(
                    student_email=student.get('email'),
                    student_name=student.get('full_name'),
                    ticket_number=ticket_info['ticket_number'],
                    subject=ticket_info['subject'],
                    new_status=status
                )
            
            return {
                'success': True,
                'ticket': ticket
            }
            
        except Exception as e:
            print(f"[Support Ticket] Error updating status: {str(e)}")
            return {'success': False, 'error': str(e)}
    
    def assign_ticket(
        self,
        ticket_id: str,
        admin_id: str
    ) -> Dict[str, Any]:
        """Assign ticket to an admin"""
        try:
            response = self.supabase.table('support_tickets').update({
                'assigned_to': admin_id,
                'status': 'in-progress' if self._get_ticket_status(ticket_id) == 'open' else None
            }).eq('id', ticket_id).execute()
            
            if response.data:
                return {'success': True, 'ticket': response.data[0]}
            return {'success': False, 'error': 'Failed to assign ticket'}
            
        except Exception as e:
            print(f"[Support Ticket] Error assigning ticket: {str(e)}")
            return {'success': False, 'error': str(e)}
    
    def get_student_tickets(self, student_id: str) -> List[Dict[str, Any]]:
        """Get all tickets for a student"""
        try:
            response = self.supabase.table('support_tickets').select('*').eq(
                'student_id', student_id
            ).order('created_at', desc=True).execute()
            
            return response.data or []
            
        except Exception as e:
            print(f"[Support Ticket] Error fetching student tickets: {str(e)}")
            return []
    
    def get_all_tickets(
        self,
        status_filter: Optional[str] = None,
        priority_filter: Optional[str] = None,
        assigned_to: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Get all tickets with optional filters"""
        try:
            query = self.supabase.table('support_tickets').select(
                '*, profiles!support_tickets_student_id_fkey(full_name, email)'
            )
            
            if status_filter:
                query = query.eq('status', status_filter)
            if priority_filter:
                query = query.eq('priority', priority_filter)
            if assigned_to:
                query = query.eq('assigned_to', assigned_to)
            
            response = query.order('created_at', desc=True).execute()
            
            return response.data or []
            
        except Exception as e:
            print(f"[Support Ticket] Error fetching tickets: {str(e)}")
            return []
    
    def get_ticket_with_replies(self, ticket_id: str) -> Dict[str, Any]:
        """Get ticket with all replies"""
        try:
            # Get ticket details
            ticket_response = self.supabase.rpc('get_ticket_details', {'ticket_uuid': ticket_id}).execute()
            
            if not ticket_response.data:
                return {'success': False, 'error': 'Ticket not found'}
            
            ticket = ticket_response.data[0]
            
            # Get replies
            replies_response = self.supabase.table('ticket_replies').select(
                '*, profiles!ticket_replies_author_id_fkey(full_name, email, role)'
            ).eq('ticket_id', ticket_id).order('created_at').execute()
            
            ticket['replies'] = replies_response.data or []
            
            return {
                'success': True,
                'ticket': ticket
            }
            
        except Exception as e:
            print(f"[Support Ticket] Error fetching ticket: {str(e)}")
            return {'success': False, 'error': str(e)}
    
    def _get_ticket_status(self, ticket_id: str) -> Optional[str]:
        """Helper to get current ticket status"""
        try:
            response = self.supabase.table('support_tickets').select('status').eq('id', ticket_id).execute()
            return response.data[0]['status'] if response.data else None
        except:
            return None
    
    def _send_ticket_created_email(
        self,
        student_email: str,
        student_name: str,
        ticket_number: str,
        subject: str
    ):
        """Send ticket creation confirmation email"""
        html = f"""
        <h2>Support Ticket Created</h2>
        <p>Hi {student_name},</p>
        <p>Your support ticket has been created successfully.</p>
        <p><strong>Ticket Number:</strong> {ticket_number}</p>
        <p><strong>Subject:</strong> {subject}</p>
        <p>Our support team will review your ticket and respond shortly.</p>
        <p>You can track your ticket status from your student dashboard.</p>
        <p>Best regards,<br>Futura Learning Support Team</p>
        """
        
        self.email_service.send_email(
            to_email=student_email,
            subject=f"Support Ticket Created: {ticket_number}",
            html_content=html
        )
    
    def _send_ticket_reply_email(
        self,
        recipient_email: str,
        recipient_name: str,
        ticket_number: str,
        subject: str,
        reply_message: str,
        author_name: str
    ):
        """Send ticket reply notification email"""
        html = f"""
        <h2>New Reply on Your Support Ticket</h2>
        <p>Hi {recipient_name},</p>
        <p><strong>{author_name}</strong> replied to your ticket:</p>
        <p><strong>Ticket:</strong> {ticket_number} - {subject}</p>
        <div style="background: #f5f5f5; padding: 15px; border-left: 3px solid #667eea; margin: 20px 0;">
            {reply_message}
        </div>
        <p>View and reply to your ticket from your dashboard.</p>
        <p>Best regards,<br>Futura Learning Support Team</p>
        """
        
        self.email_service.send_email(
            to_email=recipient_email,
            subject=f"Reply on Ticket {ticket_number}",
            html_content=html
        )
    
    def _send_status_update_email(
        self,
        student_email: str,
        student_name: str,
        ticket_number: str,
        subject: str,
        new_status: str
    ):
        """Send ticket status update email"""
        status_messages = {
            'open': 'Your ticket is now open and awaiting review.',
            'in-progress': 'Our team is actively working on your ticket.',
            'resolved': 'Your ticket has been resolved! If you need further assistance, please reply to the ticket.',
            'closed': 'Your ticket has been closed. Thank you for contacting support.'
        }
        
        html = f"""
        <h2>Ticket Status Updated</h2>
        <p>Hi {student_name},</p>
        <p>The status of your support ticket has been updated.</p>
        <p><strong>Ticket:</strong> {ticket_number} - {subject}</p>
        <p><strong>New Status:</strong> {new_status.upper()}</p>
        <p>{status_messages.get(new_status, '')}</p>
        <p>Best regards,<br>Futura Learning Support Team</p>
        """
        
        self.email_service.send_email(
            to_email=student_email,
            subject=f"Ticket {ticket_number} Status: {new_status.title()}",
            html_content=html
        )
    
    def _notify_admins_new_ticket(
        self,
        ticket_id: str,
        ticket_number: str,
        student_name: str,
        subject: str,
        priority: str
    ):
        """Notify all admins about new ticket"""
        try:
            # Get all admin IDs
            admins_response = self.supabase.table('profiles').select('id').eq('role', 'admin').execute()
            admin_ids = [admin['id'] for admin in (admins_response.data or [])]
            
            if admin_ids:
                self.notification_service.create_bulk_notifications(
                    user_ids=admin_ids,
                    notification_type='system',
                    title='New Support Ticket',
                    message=f"{student_name} created ticket: {subject} (Priority: {priority})",
                    link=f"/admin/support?ticket={ticket_id}"
                )
        except Exception as e:
            print(f"[Support Ticket] Error notifying admins: {str(e)}")
    
    def _notify_admins_ticket_reply(
        self,
        ticket_id: str,
        ticket_number: str,
        student_name: str,
        subject: str
    ):
        """Notify admins about student reply"""
        try:
            admins_response = self.supabase.table('profiles').select('id').eq('role', 'admin').execute()
            admin_ids = [admin['id'] for admin in (admins_response.data or [])]
            
            if admin_ids:
                self.notification_service.create_bulk_notifications(
                    user_ids=admin_ids,
                    notification_type='system',
                    title='Ticket Reply',
                    message=f"{student_name} replied to ticket {ticket_number}: {subject}",
                    link=f"/admin/support?ticket={ticket_id}"
                )
        except Exception as e:
            print(f"[Support Ticket] Error notifying admins: {str(e)}")


# Singleton instance
_support_ticket_service_instance = None

def get_support_ticket_service(supabase_client: Client = None) -> SupportTicketService:
    """Get or create support ticket service instance"""
    global _support_ticket_service_instance
    if _support_ticket_service_instance is None:
        if supabase_client is None:
            from utils.supabase_client import get_supabase_client
            supabase_client = get_supabase_client()
        _support_ticket_service_instance = SupportTicketService(supabase_client)
    return _support_ticket_service_instance
